// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDetectBrowser() {
  return window['go']['main']['App']['AutoDetectBrowser']();
}

export function ClearDeletionQueue() {
  return window['go']['main']['App']['ClearDeletionQueue']();
}

export function CommitDeletions() {
  return window['go']['main']['App']['CommitDeletions']();
}

export function DeleteBackups(arg1, arg2) {
  return window['go']['main']['App']['DeleteBackups'](arg1, arg2);
}

export function DeleteEntries(arg1, arg2) {
  return window['go']['main']['App']['DeleteEntries'](arg1, arg2);
}

export function DetectBrowsers() {
  return window['go']['main']['App']['DetectBrowsers']();
}

export function ExportCSV(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportCSV'](arg1, arg2, arg3, arg4);
}

export function ExportFilteredCSV(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportFilteredCSV'](arg1, arg2, arg3);
}

export function ExportHTMLWithDialog(arg1, arg2) {
  return window['go']['main']['App']['ExportHTMLWithDialog'](arg1, arg2);
}

export function ExportJSONWithDialog(arg1, arg2) {
  return window['go']['main']['App']['ExportJSONWithDialog'](arg1, arg2);
}

export function ExportSelectedCSV(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportSelectedCSV'](arg1, arg2, arg3);
}

export function GetDeletionQueueItems() {
  return window['go']['main']['App']['GetDeletionQueueItems']();
}

export function GetDeletionQueueSize() {
  return window['go']['main']['App']['GetDeletionQueueSize']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsDeletionQueued(arg1) {
  return window['go']['main']['App']['IsDeletionQueued'](arg1);
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListBrowsersWithProfiles() {
  return window['go']['main']['App']['ListBrowsersWithProfiles']();
}

export function OpenDBFolder(arg1) {
  return window['go']['main']['App']['OpenDBFolder'](arg1);
}

export function QueueDeletions(arg1, arg2) {
  return window['go']['main']['App']['QueueDeletions'](arg1, arg2);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function SearchHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchHistory'](arg1, arg2, arg3, arg4);
}

export function SearchHistoryAdvanced(arg1) {
  return window['go']['main']['App']['SearchHistoryAdvanced'](arg1);
}

export function SearchHistoryAll(arg1, arg2) {
  return window['go']['main']['App']['SearchHistoryAll'](arg1, arg2);
}

export function UnqueueDeletions(arg1) {
  return window['go']['main']['App']['UnqueueDeletions'](arg1);
}
