// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {history} from '../models';
import {main} from '../models';

export function AutoDetectBrowser():Promise<history.BrowserDetection>;

export function ClearDeletionQueue():Promise<void>;

export function CommitDeletions():Promise<main.BatchDeleteResult>;

export function DeleteBackups(arg1:string,arg2:Array<string>):Promise<number>;

export function DeleteEntries(arg1:string,arg2:Array<number>):Promise<void>;

export function DetectBrowsers():Promise<Array<main.BrowserEntry>>;

export function ExportCSV(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:string):Promise<number>;

export function ExportFilteredCSV(arg1:string,arg2:string,arg3:string):Promise<number>;

export function ExportHTMLWithDialog(arg1:string,arg2:string):Promise<number>;

export function ExportJSONWithDialog(arg1:string,arg2:string):Promise<number>;

export function ExportSelectedCSV(arg1:string,arg2:Array<number>,arg3:string):Promise<number>;

export function GetDeletionQueueItems():Promise<Array<history.HistoryEntry>>;

export function GetDeletionQueueSize():Promise<number>;

export function GetVersion():Promise<string>;

export function IsDeletionQueued(arg1:number):Promise<boolean>;

export function ListBackups(arg1:string):Promise<Array<main.BackupSnapshot>>;

export function ListBrowsersWithProfiles():Promise<Array<main.BrowserWithProfiles>>;

export function OpenDBFolder(arg1:string):Promise<string>;

export function QueueDeletions(arg1:string,arg2:Array<number>):Promise<number>;

export function RestoreBackup(arg1:string,arg2:string):Promise<string>;

export function SearchHistory(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.HistoryResult>;

export function SearchHistoryAdvanced(arg1:main.SearchHistoryOptions):Promise<main.HistoryResult>;

export function SearchHistoryAll(arg1:string,arg2:string):Promise<Array<history.HistoryEntry>>;

export function UnqueueDeletions(arg1:Array<number>):Promise<number>;
